// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: code.jflex

package com.cunoc.CaptchaForge.Model.JflexAndCup.CC;

import java_cup.runtime.Symbol;
import java.util.ArrayList;
import java.io.StringReader;
import com.cunoc.CaptchaForge.Model.Analyzer.ErrorTypeInTheInterpreter;
import com.cunoc.CaptchaForge.Model.Analyzer.ReportErrorInterpreter;
import com.cunoc.CaptchaForge.Model.Analyzer.Token;


@SuppressWarnings("fallthrough")
public class LexemaCC implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\4\2\22\0\1\1\1\0\1\3\11\0"+
    "\1\4\2\0\1\5\1\0\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\3\0\1\14\1\0\1\15\1\16\1\17"+
    "\2\0\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\25\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\25\1\37\1\40\1\41\1\42\1\43\1\25"+
    "\1\44\1\45\1\25\1\46\1\47\1\50\1\0\1\51"+
    "\1\0\4\25\1\52\3\25\1\53\4\25\1\54\1\55"+
    "\2\25\1\56\1\57\2\25\1\60\4\25\1\61\1\1"+
    "\1\62\7\0\1\2\32\0\1\1\u01df\0\1\1\177\0"+
    "\13\1\35\0\2\2\5\0\1\1\57\0\1\1\240\0"+
    "\1\1\377\0\u0100\63";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\2\11\1\12\1\13\1\11\1\14\1\15"+
    "\1\0\1\16\1\0\11\11\1\17\4\11\1\20\1\11"+
    "\1\21\1\11\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\14\11\1\30\1\11\1\31\10\11\1\32\1\11\1\33"+
    "\1\11\1\34\2\11\1\35\4\11\1\36\3\11\1\37"+
    "\1\40\1\41\1\42\1\43\2\11\1\44";

  private static int [] zzUnpackAction() {
    int [] result = new int[91];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\64\0\64\0\64\0\64"+
    "\0\64\0\64\0\320\0\u0104\0\64\0\64\0\u0138\0\64"+
    "\0\64\0\234\0\64\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c"+
    "\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340\0\320\0\u0374\0\u03a8"+
    "\0\u03dc\0\u0410\0\320\0\u0444\0\320\0\u0478\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\u04ac\0\u04e0\0\u0514\0\u0548"+
    "\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8"+
    "\0\320\0\u071c\0\320\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\u0854\0\u0888\0\u08bc\0\320\0\u08f0\0\320\0\u0924\0\320"+
    "\0\u0958\0\u098c\0\320\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\320"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\320\0\320\0\320\0\320\0\320"+
    "\0\u0b2c\0\u0b60\0\320";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[91];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\6\2\1\7\1\10"+
    "\1\11\1\12\2\13\1\14\23\13\1\15\1\2\1\16"+
    "\7\13\1\17\1\20\1\21\66\0\2\3\61\0\3\22"+
    "\1\23\43\22\1\24\14\22\20\0\26\13\3\0\10\13"+
    "\23\0\26\13\3\0\1\25\7\13\23\0\26\13\3\0"+
    "\1\13\1\26\6\13\3\0\2\22\1\0\60\22\21\0"+
    "\1\13\1\27\1\30\1\31\3\13\1\32\1\33\1\13"+
    "\1\34\2\13\1\35\1\36\1\13\1\37\1\40\4\13"+
    "\3\0\10\13\23\0\26\13\3\0\5\13\1\41\2\13"+
    "\23\0\15\13\1\42\1\13\1\43\2\13\1\44\3\13"+
    "\3\0\10\13\23\0\2\13\1\45\23\13\3\0\10\13"+
    "\23\0\10\13\1\46\15\13\3\0\10\13\11\0\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\4\0\4\13\1\55"+
    "\21\13\3\0\10\13\23\0\13\13\1\56\1\57\11\13"+
    "\3\0\10\13\23\0\10\13\1\60\15\13\3\0\10\13"+
    "\23\0\16\13\1\61\7\13\3\0\10\13\23\0\4\13"+
    "\1\62\11\13\1\63\7\13\3\0\10\13\23\0\4\13"+
    "\1\64\3\13\1\65\15\13\3\0\10\13\23\0\26\13"+
    "\3\0\6\13\1\66\1\13\23\0\3\13\1\67\22\13"+
    "\3\0\10\13\23\0\21\13\1\70\4\13\3\0\10\13"+
    "\23\0\23\13\1\71\2\13\3\0\10\13\23\0\1\72"+
    "\25\13\3\0\10\13\23\0\6\13\1\73\17\13\3\0"+
    "\10\13\23\0\16\13\1\74\7\13\3\0\10\13\23\0"+
    "\14\13\1\75\11\13\3\0\10\13\23\0\21\13\1\76"+
    "\4\13\3\0\10\13\23\0\12\13\1\77\13\13\3\0"+
    "\10\13\23\0\1\100\25\13\3\0\10\13\23\0\24\13"+
    "\1\101\1\13\3\0\10\13\23\0\21\13\1\102\4\13"+
    "\3\0\10\13\23\0\26\13\3\0\2\13\1\103\5\13"+
    "\23\0\25\13\1\104\3\0\10\13\23\0\21\13\1\105"+
    "\4\13\3\0\10\13\23\0\3\13\1\106\22\13\3\0"+
    "\10\13\23\0\22\13\1\107\3\13\3\0\10\13\23\0"+
    "\11\13\1\110\14\13\3\0\10\13\23\0\10\13\1\111"+
    "\15\13\3\0\10\13\23\0\4\13\1\112\21\13\3\0"+
    "\10\13\23\0\13\13\1\113\12\13\3\0\10\13\23\0"+
    "\21\13\1\114\4\13\3\0\10\13\23\0\12\13\1\115"+
    "\13\13\3\0\10\13\23\0\26\13\3\0\4\13\1\116"+
    "\3\13\23\0\15\13\1\117\10\13\3\0\10\13\23\0"+
    "\21\13\1\120\4\13\3\0\10\13\23\0\15\13\1\121"+
    "\10\13\3\0\10\13\23\0\2\13\1\122\23\13\3\0"+
    "\10\13\23\0\1\123\25\13\3\0\10\13\23\0\4\13"+
    "\1\124\21\13\3\0\10\13\23\0\26\13\3\0\3\13"+
    "\1\125\4\13\23\0\14\13\1\126\11\13\3\0\10\13"+
    "\23\0\14\13\1\127\11\13\3\0\10\13\23\0\21\13"+
    "\1\130\4\13\3\0\10\13\23\0\17\13\1\131\6\13"+
    "\3\0\10\13\23\0\4\13\1\132\21\13\3\0\10\13"+
    "\23\0\1\133\25\13\3\0\10\13\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2964];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\6\11\2\1\2\11\1\1\2\11"+
    "\1\0\1\11\1\0\22\1\6\11\57\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[91];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

     public LexemaCC(String in) {
    this.zzReader = new StringReader(in);
    }
    /*START-CODE*/
    private ArrayList<ReportErrorInterpreter> listError = new ArrayList();
  
    private void print(String token) {
        //System.out.println(" < " + yytext() + " > <Linea\"" + (yyline + 1) + "\">" + "<Columna\"" + (yycolumn+1) + "\">");
    }

    private void addError(){
        print("error");
        ErrorTypeInTheInterpreter type = ErrorTypeInTheInterpreter.LEXICON;
        Token toke = new Token(yyline + 1, yycolumn + 1, yytext());
        this.listError.add(new ReportErrorInterpreter(type, toke, ""));
    }
    public ArrayList<ReportErrorInterpreter> getListError() {
        return this.listError;
    }

    /*FINAL-CODE*/


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexemaCC(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return new java_cup.runtime.Symbol(SymCC.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { //MANEJAR EL ERROR LEXICO
                        print("ERROR");
                        addError();
            }
          // fall through
          case 37: break;
          case 2:
            { /* print(); */
            }
          // fall through
          case 38: break;
          case 3:
            { print(","); return new Symbol(SymCC.COMA,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 39: break;
          case 4:
            { print("/"); return new Symbol(SymCC.BAR,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 40: break;
          case 5:
            { print(":"); return new Symbol(SymCC.COLNO,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 41: break;
          case 6:
            { print("<" ); return new Symbol(SymCC.OPEN ,yyline,yycolumn,yytext());
            }
          // fall through
          case 42: break;
          case 7:
            { print("="); return new Symbol(SymCC.EQUAL,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 43: break;
          case 8:
            { print(">" ); return new Symbol(SymCC.CLOSE ,yyline,yycolumn,yytext());
            }
          // fall through
          case 44: break;
          case 9:
            { String lowercaseText = yytext().toLowerCase();
                                     switch(lowercaseText) {
                                         case "version":
                                            print("version"); 
                                            return new Symbol(SymCC.VERSION ,yyline,yycolumn,yytext());
                                        default:
                                            print("ERROR");
                                            addError();
                                            break;
                                     }
            }
          // fall through
          case 45: break;
          case 10:
            { print("["); return new Symbol(SymCC.BRACKETS_O ,yyline,yycolumn,yytext());
            }
          // fall through
          case 46: break;
          case 11:
            { print("]"); return new Symbol(SymCC.BRACKETS_C ,yyline,yycolumn,yytext());
            }
          // fall through
          case 47: break;
          case 12:
            { print("{"); return new Symbol(SymCC.KEYS_O ,yyline,yycolumn,yytext());
            }
          // fall through
          case 48: break;
          case 13:
            { print("}"); return new Symbol(SymCC.KEYS_C ,yyline,yycolumn,yytext());
            }
          // fall through
          case 49: break;
          case 14:
            { print("STRING"); return new Symbol(SymCC.STRING ,yyline,yycolumn,yytext());
            }
          // fall through
          case 50: break;
          case 15:
            { print("C_P"); return new Symbol(SymCC.C_P,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 51: break;
          case 16:
            { print("C_BR"); return new Symbol(SymCC.C_BR,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 52: break;
          case 17:
            { print("/"); return new Symbol(SymCC.C_CC,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 53: break;
          case 18:
            { print("C_H1"); return new Symbol(SymCC.C_H1,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 54: break;
          case 19:
            { print("C_H2"); return new Symbol(SymCC.C_H2,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 55: break;
          case 20:
            { print("C_H3"); return new Symbol(SymCC.C_H3,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 56: break;
          case 21:
            { print("C_H4"); return new Symbol(SymCC.C_H4,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 57: break;
          case 22:
            { print("C_H5"); return new Symbol(SymCC.C_H5,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 58: break;
          case 23:
            { print("C_H6"); return new Symbol(SymCC.C_H6,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 59: break;
          case 24:
            { print("C_DIV"); return new Symbol(SymCC.C_DIV,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 60: break;
          case 25:
            { print("C_IMG"); return new Symbol(SymCC.C_IMG,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 61: break;
          case 26:
            { print("C_BODY"); return new Symbol(SymCC.C_BODY,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 62: break;
          case 27:
            { print("C_HEAD"); return new Symbol(SymCC.C_HEAD,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 63: break;
          case 28:
            { print("C_LINK"); return new Symbol(SymCC.C_LINK,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 64: break;
          case 29:
            { print("C_SPAM"); return new Symbol(SymCC.C_SPAM,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 65: break;
          case 30:
            { print("C_INPUT"); return new Symbol(SymCC.C_INPUT,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 66: break;
          case 31:
            { print("C_TITLE"); return new Symbol(SymCC.C_TITLE,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 67: break;
          case 32:
            { print("version"); return new Symbol(SymCC.VERSION ,yyline,yycolumn,yytext());
            }
          // fall through
          case 68: break;
          case 33:
            { print("C_BUTTON"); return new Symbol(SymCC.C_BUTTON,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 69: break;
          case 34:
            { print("C_OPTION"); return new Symbol(SymCC.C_OPTION,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 70: break;
          case 35:
            { print("C_SELECT"); return new Symbol(SymCC.C_SELECT,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 71: break;
          case 36:
            { print("C_TEXTAREA"); return new Symbol(SymCC.C_TEXTAREA,yyline,yycolumn, (yytext()));
            }
          // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
