
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.CaptchaForge.Model.JflexAndCup.CC;

/** CUP generated class containing symbol constants. */
public class SymCC {
  /* terminals */
  public static final int COLNO = 10;
  public static final int C_DIV = 24;
  public static final int CLOSE = 3;
  public static final int EQUAL = 9;
  public static final int C_BR = 26;
  public static final int C_SPAM = 19;
  public static final int BRACKETS_O = 7;
  public static final int C_TITLE = 16;
  public static final int C_OPTION = 23;
  public static final int KEYS_O = 5;
  public static final int C_SELECT = 22;
  public static final int STRING = 13;
  public static final int COMA = 11;
  public static final int BRACKETS_C = 8;
  public static final int C_IMG = 25;
  public static final int EOF = 0;
  public static final int KEYS_C = 6;
  public static final int C_P = 34;
  public static final int error = 1;
  public static final int C_HEAD = 15;
  public static final int C_TEXTAREA = 21;
  public static final int VERSION = 4;
  public static final int C_LINK = 17;
  public static final int C_INPUT = 20;
  public static final int OPEN = 2;
  public static final int C_H6 = 33;
  public static final int C_BUTTON = 27;
  public static final int BAR = 12;
  public static final int C_H5 = 32;
  public static final int C_CC = 14;
  public static final int C_H4 = 31;
  public static final int C_H3 = 30;
  public static final int C_BODY = 18;
  public static final int C_H2 = 29;
  public static final int C_H1 = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN",
  "CLOSE",
  "VERSION",
  "KEYS_O",
  "KEYS_C",
  "BRACKETS_O",
  "BRACKETS_C",
  "EQUAL",
  "COLNO",
  "COMA",
  "BAR",
  "STRING",
  "C_CC",
  "C_HEAD",
  "C_TITLE",
  "C_LINK",
  "C_BODY",
  "C_SPAM",
  "C_INPUT",
  "C_TEXTAREA",
  "C_SELECT",
  "C_OPTION",
  "C_DIV",
  "C_IMG",
  "C_BR",
  "C_BUTTON",
  "C_H1",
  "C_H2",
  "C_H3",
  "C_H4",
  "C_H5",
  "C_H6",
  "C_P"
  };
}

