
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.CaptchaForge.Model.JflexAndCup.Scripting;

/** CUP generated class containing symbol constants. */
public class SymScripting {
  /* terminals */
  public static final int GREATER_THAN_EQUAL = 20;
  public static final int CHAR = 5;
  public static final int ALERT_INFO = 52;
  public static final int DESC = 46;
  public static final int LESS_THAN_EQUAL = 18;
  public static final int INTEGER = 2;
  public static final int REPEAT = 41;
  public static final int PARENTHESIS_OPEN = 29;
  public static final int CARACTER_ALEATORIO = 50;
  public static final int INIT = 34;
  public static final int GREATER_THAN = 19;
  public static final int REVERSE = 49;
  public static final int NOT = 23;
  public static final int SEMICOLON = 8;
  public static final int AND = 22;
  public static final int OR = 21;
  public static final int LETIMPAR_NUM = 48;
  public static final int EXIT = 53;
  public static final int IF = 37;
  public static final int MODO = 32;
  public static final int SUBTRACTION = 25;
  public static final int NUM_ALEATORIO = 51;
  public static final int ID = 7;
  public static final int LETPAR_NUM = 47;
  public static final int NOT_THE_SAME = 16;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int DECIMAL = 3;
  public static final int EQUAL = 14;
  public static final int TRUE = 10;
  public static final int error = 1;
  public static final int HUNTIL = 42;
  public static final int COMA = 9;
  public static final int BRACKETS_CLOSE = 31;
  public static final int AND_INIT = 36;
  public static final int THENWHILE = 44;
  public static final int REDIRECT = 54;
  public static final int ASC = 45;
  public static final int ELSE = 40;
  public static final int WHILE = 43;
  public static final int INSERT = 33;
  public static final int ADDITION = 24;
  public static final int THEN = 38;
  public static final int END = 39;
  public static final int STRING = 6;
  public static final int START_INIT = 35;
  public static final int TEXT = 13;
  public static final int FALSE = 11;
  public static final int DIVISION = 26;
  public static final int SAME_AS = 15;
  public static final int PARENTHESIS_CLOSE = 28;
  public static final int LESS_THAN = 17;
  public static final int REAL_NUMEBERS = 12;
  public static final int MULTIPLICATION = 27;
  public static final int BRACKETS_OPEN = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "ID",
  "SEMICOLON",
  "COMA",
  "TRUE",
  "FALSE",
  "REAL_NUMEBERS",
  "TEXT",
  "EQUAL",
  "SAME_AS",
  "NOT_THE_SAME",
  "LESS_THAN",
  "LESS_THAN_EQUAL",
  "GREATER_THAN",
  "GREATER_THAN_EQUAL",
  "OR",
  "AND",
  "NOT",
  "ADDITION",
  "SUBTRACTION",
  "DIVISION",
  "MULTIPLICATION",
  "PARENTHESIS_CLOSE",
  "PARENTHESIS_OPEN",
  "BRACKETS_OPEN",
  "BRACKETS_CLOSE",
  "MODO",
  "INSERT",
  "INIT",
  "START_INIT",
  "AND_INIT",
  "IF",
  "THEN",
  "END",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "WHILE",
  "THENWHILE",
  "ASC",
  "DESC",
  "LETPAR_NUM",
  "LETIMPAR_NUM",
  "REVERSE",
  "CARACTER_ALEATORIO",
  "NUM_ALEATORIO",
  "ALERT_INFO",
  "EXIT",
  "REDIRECT"
  };
}

