
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cunoc.CaptchaForge.Model.JflexAndCup.CaptchaReportDataBase;

/** CUP generated class containing symbol constants. */
public class SymCaptchaReportDataBase {
  /* terminals */
  public static final int COLNO = 16;
  public static final int MULTIPLICAR = 6;
  public static final int DIVIDIR = 5;
  public static final int EQUAL = 7;
  public static final int REAL_NUMEBERS = 10;
  public static final int STRING_DATE = 11;
  public static final int BRACKETS_O = 12;
  public static final int ID = 18;
  public static final int KEYS_O = 14;
  public static final int COMA = 17;
  public static final int STRING = 2;
  public static final int BRACKETS_C = 13;
  public static final int NUMBER_FAILL = 20;
  public static final int NUMBER_HITS = 19;
  public static final int EOF = 0;
  public static final int KEYS_C = 15;
  public static final int RESTAR = 4;
  public static final int PARENTESIS_C = 9;
  public static final int error = 1;
  public static final int LAST_DATA = 21;
  public static final int PARENTESIS_A = 8;
  public static final int SUMAR = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "SUMAR",
  "RESTAR",
  "DIVIDIR",
  "MULTIPLICAR",
  "EQUAL",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "REAL_NUMEBERS",
  "STRING_DATE",
  "BRACKETS_O",
  "BRACKETS_C",
  "KEYS_O",
  "KEYS_C",
  "COLNO",
  "COMA",
  "ID",
  "NUMBER_HITS",
  "NUMBER_FAILL",
  "LAST_DATA"
  };
}

